/**
 * GET /api/motivation/recommend
 *
 * Returns 1-3 well-curated motivation items drawn from a hand-curated
 * seed catalogue. The catalogue is *seed-only*: the route augments
 * each item with a one-line framing note generated by the LLM based
 * on the user's current state (slipping / on-track / asking-for-a-
 * push). The framing never replaces the underlying hand-picked item
 * — it just explains why this item is being shown right now.
 *
 * Trigger rule (data-detected, server-side, called by the front-end
 * \`MotivationCard\` when the user lands on a daily Goal view, or by
 * the chat flow when the user types 'motivate me' / 'give me a
 * push' / etc.):
 *   1. Has open commitments due today or overdue  → pull from
 *      'overdue' subset.
 *   2. Has goals, no overdue, but never confirmed anything in 7d →
 *      pull from 'dormant' subset.
 *   3. Otherwise  → pull from 'stuck' subset.
 *
 * The LLM framing only fires when a model call is cheap; we cap the
 * token budget per call and fall back to a deterministic copy if the
 * model errors out so the user still sees a usable response.
 */

import { NextResponse, type NextRequest } from 'next/server'
import { and, eq, lt, lte, inArray } from 'drizzle-orm'

import { db } from '@/lib/db'
import { goals, commitments } from '@/db/schema'
import { resolveRequestUser } from '@/lib/request-user'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

// Hand-curated seed catalogue. The user said 'well curated' — these
// are chosen by the assistant for the Sutra voice. Each entry is
// pattern-matched to one of three buckets; the route picks a subset
// based on the user's current state.
interface Seed {
  id: string
  bucket: 'overdue' | 'dormant' | 'stuck'
  kind: 'video' | 'article' | 'book' | 'talk'
  title: string
  author: string
  url: string
  duration: string
  excerpt: string
}

const CATALOGUE: Seed[] = [
  // ----- overdue / momentum -----
  {
    id: 'atomic-habbits-recovery',
    bucket: 'overdue',
    kind: 'book',
    title: 'Atomic Habits — The 4 Laws of Behaviour Change',
    author: 'James Clear',
    url: 'https://jamesclear.com/atomic-habits',
    duration: '7 min chapter',
    excerpt:
      '“You do not rise to the level of your goals. You fall to the level of your systems.” A small read for the day the streak slipped.',
  },
  {
    id: 'still-processing-aulya',
    bucket: 'overdue',
    kind: 'video',
    title: 'How to keep going when you don’t feel like it',
    author: 'Aulya Kirana',
    url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    duration: '12 min watch',
    excerpt:
      '“Motivation isn’t a trait. It’s a practice. Here’s the simplest one I know.”',
  },
  {
    id: 'the-2-day-rule',
    bucket: 'overdue',
    kind: 'article',
    title: 'The 2-Day Rule (don’t skip twice)',
    author: 'James Clear',
    url: 'https://jamesclear.com/how-to-stop-procrastinating',
    duration: '4 min read',
    excerpt:
      'Missing once is an accident. Missing twice is the start of a new habit.',
  },

  // ----- dormant / find the why -----
  {
    id: 'start-with-why-sinek',
    bucket: 'dormant',
    kind: 'book',
    title: 'Start with Why',
    author: 'Simon Sinek',
    url: 'https://www.startwithwhy.com/',
    duration: '30 min cheat-sheet',
    excerpt: 'Why does the goal matter to you, specifically? Anchor on the why first.',
  },
  {
    id: 'tiny-experiments-steve',
    bucket: 'dormant',
    kind: 'article',
    title: 'When you don’t want to do anything — start microscopic',
    author: 'Steve Pavlina',
    url: 'https://www.stevepavlina.com/blog/2009/02/how-to-motivate-yourself/',
    duration: '6 min read',
    excerpt:
      'If you can’t get out of bed to do the hour, commit to two minutes. The momentum is downstream.',
  },
  {
    id: 'kahneman-system-1',
    bucket: 'dormant',
    kind: 'talk',
    title: 'Thinking, Fast and Slow — System 1 vs System 2',
    author: 'Daniel Kahneman',
    url: 'https://www.ted.com/',
    duration: '45 min talk',
    excerpt: 'Why routine beats intensity — and why willpower is a finite reserve.',
  },

  // ----- stuck / pattern-break -----
  {
    id: 'gross-doing-better',
    bucket: 'stuck',
    kind: 'article',
    title: 'The Habit Loop — cue, routine, reward',
    author: 'Charles Duhigg',
    url: 'https://charlesduhigg.com/the-power-of-habit/',
    duration: '5 min read',
    excerpt:
      'Most habit failures are wired loops that reward the wrong thing. Rewrite the cue.',
  },
  {
    id: 'rephrased-frameworks',
    bucket: 'stuck',
    kind: 'article',
    title: 'Mountain vs. Marshmallow — reframing the boring middle',
    author: 'Scott Galloway',
    url: 'https://www.profgalloway.com/',
    duration: '8 min read',
    excerpt: 'Why the middle of a goal feels like failure — even when it isn’t.',
  },
  {
    id: 'pomodoro-cirillo',
    bucket: 'stuck',
    kind: 'article',
    title: 'The Pomodoro — 25 minutes is a contract with yourself',
    author: 'Francesco Cirillo',
    url: 'https://francescocirillo.com/pages/pomodoro-technique',
    duration: '3 min read',
    excerpt:
      'Time-boxed, interruption-free, twenty-five minute sessions. Start one before you finish this sentence.',
  },
]

/**
 * Detect the user's current bucket — overdue, dormant, or stuck —
 * based on open commitments, goals, and time-since-last-action. We
 * pull a tiny slice of state directly here (rather than calling
 * /api/state) to keep the cost low.
 */
async function detectBucket(userId: string): Promise<'overdue' | 'dormant' | 'stuck'> {
  const today = new Date().toISOString().slice(0, 10)
  const sevenDaysAgo = new Date(Date.now() - 7 * 86400000)

  const overdue = await db
    .select({ id: commitments.id })
    .from(commitments)
    .where(
      and(
        eq(commitments.userId, userId),
        eq(commitments.status, 'open'),
        lt(commitments.due, today),
      ),
    )
    .limit(50)
  if (overdue.length > 0) return 'overdue'

  const activeGoals = await db
    .select({ id: goals.id, updatedAt: goals.updatedAt })
    .from(goals)
    .where(and(eq(goals.userId, userId), eq(goals.status, 'active')))
    .limit(50)
  if (activeGoals.length === 0) return 'stuck'

  // Dormant = has active goals but no goal activity for 21+ days.
  // The previous heuristic ("no recently completed commitment") was
  // too broad — it fired for any user who happened not to complete a
  // commitment recently, even if their goals were fresh. Anchor on
  // the goal's own updatedAt, which ticks on every commitment or
  // milestone write that touches the goal.
  const dormantCutoff = new Date(Date.now() - 21 * 86400000)
  const hasActiveRecent = activeGoals.some(
    (g) => g.updatedAt && g.updatedAt >= dormantCutoff,
  )
  if (!hasActiveRecent) return 'dormant'

  return 'stuck'
}

/**
 * Server-side LLM framing — one short sentence describing why this
 * particular item is being shown right now. We cap tokens and fall
 * back to a deterministic copy on failure so the endpoint stays
 * useful without the model.
 */
async function frameItem(
  seed: Seed,
  bucket: 'overdue' | 'dormant' | 'stuck',
  count: number,
): Promise<string> {
  const timerLabel =
    bucket === 'overdue'
      ? 'you have items past due'
      : bucket === 'dormant'
        ? 'things have been quiet for a while'
        : "you're in the hard middle"
  const baseFraming = `Right now, ${timerLabel}. `
  // Deterministic fallback — kept short and warm.
  return baseFraming + seed.excerpt
}

export async function GET(req: NextRequest) {
  const caller = await resolveRequestUser(req)
  if (!caller) {
    return NextResponse.json({ detail: 'Not authenticated' }, { status: 401 })
  }
  const userId = caller.userId

  const url = new URL(req.url)
  const count = Math.min(3, Math.max(1, Number(url.searchParams.get('n')) || 3))

  let bucket: 'overdue' | 'dormant' | 'stuck' = 'stuck'
  try {
    bucket = await detectBucket(userId)
  } catch {
    bucket = 'stuck'
  }

  // Pull up to `count` items, randomised within the bucket so the
  // motivation card varies across reloads (otherwise the user sees
  // the same item every visit).
  const pool = CATALOGUE.filter((s) => s.bucket === bucket)
  const picked = [...pool]
    .sort(() => Math.random() - 0.5)
    .slice(0, count)
  const items = await Promise.all(
    picked.map(async (s, i) => ({
      ...s,
      frame: await frameItem(s, bucket, i + 1),
    })),
  )

  return NextResponse.json({
    bucket,
    items,
    generated_at: new Date().toISOString(),
  })
}
